model_name: microsoft/deberta-v3-small
learning_rate: 5e-5
scheduler: cosine
gradient_checkpointing: false
gradient_accumulation_steps: 6
per_device_train_batch_size: 1
per_device_eval_batch_size: 3
warmup_steps: 100
eval_steps: 50
save_steps: 50
max_length: 4096
num_train_epochs: 3
summeval_path: ./datasets/InformativenessRating_dataset/
output_dir: ./models/inf_reward_model_deberta_v3_small/
datasets:
  - newsroom_local