model_name: OpenAssistant/reward-model-deberta-v3-large
learning_rate: 5e-5
scheduler: constant
gradient_checkpointing: true
gradient_accumulation_steps: 6
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
warmup_steps: 0
eval_steps: 50
save_steps: 50
max_length: 4096
num_train_epochs: 3
auto_find_batch_size: false
report_to:
  - tensorboard
summeval_path: /root/datasets/sensitivity_equal_chunks/RelevanceRating_dataset/
output_dirs:
  - ./runs/newsroom-incremental/deberta-small/RelevanceRating/train0/
  - ./runs/newsroom-incremental/deberta-small/RelevanceRating/train10/
  - ./runs/newsroom-incremental/deberta-small/RelevanceRating/train20/
  - ./runs/newsroom-incremental/deberta-small/RelevanceRating/train30/
  - ./runs/newsroom-incremental/deberta-small/RelevanceRating/train40/
  - ./runs/newsroom-incremental/deberta-small/RelevanceRating/train50/
  - ./runs/newsroom-incremental/deberta-small/RelevanceRating/train60/
  - ./runs/newsroom-incremental/deberta-small/RelevanceRating/train70/
  - ./runs/newsroom-incremental/deberta-small/RelevanceRating/train80/
  - ./runs/newsroom-incremental/deberta-small/RelevanceRating/train90/
  - ./runs/newsroom-incremental/deberta-small/RelevanceRating/train100/
train_splits:
  - []
  - [train_0]
  - [train_0, train_1]
  - [train_0, train_1, train_2]
  - [train_0, train_1, train_2, train_3]
  - [train_0, train_1, train_2, train_3, train_4]
  - [train_0, train_1, train_2, train_3, train_4, train_5]
  - [train_0, train_1, train_2, train_3, train_4, train_5, train_6]
  - [train_0, train_1, train_2, train_3, train_4, train_5, train_6, train_7]
  - [train_0, train_1, train_2, train_3, train_4, train_5, train_6, train_7, train_8]
  - [train_0, train_1, train_2, train_3, train_4, train_5, train_6, train_7, train_8, train_9]
datasets:
  - newsroom_local
